python run_svm.py -f 0 -l L2 -t T1
python run_svm.py -f 1 -l L2 -t T1
python run_svm.py -f 0 -l L2 -t T2
python run_svm.py -f 1 -l L2 -t T2
python run_svm.py -f 0 -l L3 -t T1
python run_svm.py -f 1 -l L3 -t T1
python run_svm.py -f 0 -l L3 -t T2
python run_svm.py -f 1 -l L3 -t T2
python run_svm.py -f 0 -l L6 -t T1
python run_svm.py -f 1 -l L6 -t T1
python run_svm.py -f 0 -l L6 -t T2
python run_svm.py -f 1 -l L6 -t T2
python run_svm.py -f 0 -l L8 -t T1
python run_svm.py -f 1 -l L8 -t T1
python run_svm.py -f 0 -l L8 -t T2
python run_svm.py -f 1 -l L8 -t T2
python run_svm.py -f 0 -l L10 -t T1
python run_svm.py -f 1 -l L10 -t T1
python run_svm.py -f 0 -l L10 -t T2
python run_svm.py -f 1 -l L10 -t T2
python run_svm.py -f 0 -l L11 -t T1
python run_svm.py -f 1 -l L11 -t T1
python run_svm.py -f 0 -l L11 -t T2
python run_svm.py -f 1 -l L11 -t T2